// ProspectAI — /api/admin/intent
// Admin-only: view and manage intent data stored in Redis
// GET  — returns all intent:* keys, their data, and daily counter
// DELETE ?domain=x — removes a single intent domain
// DELETE ?all=1    — clears all intent:* keys

import { getAuth } from '@clerk/nextjs/server';
import { Redis } from '@upstash/redis';

const redis = new Redis({
  url: process.env.KV_REST_API_URL,
    token: process.env.KV_REST_API_TOKEN,
    });

    const ADMIN_USER_ID = 'user_3BSgI2SWsJ9xBJeTxxN4mOWqGRM';

    function dailyCounterKey() {
      const d = new Date().toISOString().slice(0, 10);
        return `intent:daily:${d}`;
        }

        export default async function handler(req, res) {
          const { userId } = getAuth(req);
            if (!userId || userId !== ADMIN_USER_ID) {
                return res.status(403).json({ error: 'Forbidden' });
                  }

                    // GET — list all intent domains + daily counter
                      if (req.method === 'GET') {
                          try {
                                // Scan for all intent:* keys (exclude daily counter keys)
                                      let cursor = '0';
                                            const allKeys = [];
                                                  do {
                                                          const [nextCursor, keys] = await redis.scan(cursor, { match: 'intent:*', count: 100 });
                                                                  cursor = nextCursor;
                                                                          allKeys.push(...keys);
                                                                                } while (cursor !== '0');

                                                                                      const domainKeys = allKeys.filter(k => !k.startsWith('intent:daily:'));
                                                                                            const dailyKeys = allKeys.filter(k => k.startsWith('intent:daily:'));

                                                                                                  // Fetch all domain data
                                                                                                        const entries = await Promise.all(
                                                                                                                domainKeys.map(async key => {
                                                                                                                          const domain = key.replace('intent:', '');
                                                                                                                                    const raw = await redis.get(key);
                                                                                                                                              const data = raw ? (typeof raw === 'string' ? JSON.parse(raw) : raw) : {};
                                                                                                                                                        // Get TTL
                                                                                                                                                                  const ttl = await redis.ttl(key);
                                                                                                                                                                            return {
                                                                                                                                                                                        domain,
                                                                                                                                                                                                    org_name: data.org_name || domain,
                                                                                                                                                                                                                intent_strength: data.intent_strength || 'high',
                                                                                                                                                                                                                            intent_signals: data.intent_signals || [],
                                                                                                                                                                                                                                        updated_at: data.updated_at || null,
                                                                                                                                                                                                                                                    source: data.source || 'unknown',
                                                                                                                                                                                                                                                                ttl_seconds: ttl,
                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                              // Sort by updated_at desc
                                                                                                                                                                                                                                                                                                    entries.sort((a, b) => new Date(b.updated_at || 0) - new Date(a.updated_at || 0));
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                          // Daily counter
                                                                                                                                                                                                                                                                                                                const counterKey = dailyCounterKey();
                                                                                                                                                                                                                                                                                                                      const todayCount = parseInt((await redis.get(counterKey)) || '0', 10);
                                                                                                                                                                                                                                                                                                                            const dailyLimit = parseInt(process.env.INTENT_DAILY_LIMIT || '25', 10);
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                  // Past daily counters (last 7 days)
                                                                                                                                                                                                                                                                                                                                        const today = new Date();
                                                                                                                                                                                                                                                                                                                                              const history = await Promise.all(
                                                                                                                                                                                                                                                                                                                                                      Array.from({ length: 7 }, (_, i) => {
                                                                                                                                                                                                                                                                                                                                                                const d = new Date(today);
                                                                                                                                                                                                                                                                                                                                                                          d.setDate(d.getDate() - i);
                                                                                                                                                                                                                                                                                                                                                                                    const key = `intent:daily:${d.toISOString().slice(0, 10)}`;
                                                                                                                                                                                                                                                                                                                                                                                              return redis.get(key).then(v => ({
                                                                                                                                                                                                                                                                                                                                                                                                          date: d.toISOString().slice(0, 10),
                                                                                                                                                                                                                                                                                                                                                                                                                      count: parseInt(v || '0', 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                }));
                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                            entries,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    total: entries.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            daily: { count: todayCount, limit: dailyLimit, key: counterKey },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    history,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // DELETE — remove one domain or all
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (req.method === 'DELETE') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { domain, all } = req.query;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (all === '1') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Clear all intent domain keys (not daily counters)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let cursor = '0';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const toDelete = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              do {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const [nextCursor, keys] = await redis.scan(cursor, { match: 'intent:*', count: 100 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor = nextCursor;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            toDelete.push(...keys.filter(k => !k.startsWith('intent:daily:')));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } while (cursor !== '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (toDelete.length > 0) await redis.del(...toDelete);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(200).json({ ok: true, deleted: toDelete.length });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (domain) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await redis.del(`intent:${domain}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(200).json({ ok: true, deleted: domain });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(400).json({ error: 'Provide ?domain=x or ?all=1' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(405).json({ error: 'Method not allowed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
